### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by rekado** [kmezhoud/bioCancer#1]
I was about to package bioCancer for GNU Guix when I noticed that "the help files" are released under a non-commercial CC license, thereby making them non-free according to the Free System Distribution Guidelines.

Could you please clarify what files are released under that license?

Thanks!

**Comment by kmezhoud** [comment]
Thanks for your interest to bioCancer.
I am ready to change the existing license for GNU Guix.
Let me know what I have to do.
One thing, bioCancer is hosted at bioconductor
<https://bioconductor.org/packages/release/bioc/html/bioCancer.html>  open
source project.
I am curious what to you mean by "package bioCancer for GNU..."
Thanks
Karim

**Comment by rekado** [comment]
Thank you for being open to adjusting the license!

Of all the CC licenses only the NC variant is deemed non-free, preventing distribution by all free software distributions of GNU/Linux (such as Debian, Fedora, and Guix System, among others).  The CC-BY-SA (which requires attribution and sharing alike) is considered a free license, just as CC-BY (only requiring attribution).

GNU Guix is a package manager designed around reproducibility.  By making R packages available in Guix, users can be sure that the complex environments their research requires can be reproduced bit for bit, even after many years, and with only a simple command --- all that without resorting to binary blobs, virtual machines, or opaque disk archives.

Why Guix is a good idea for high performance computing (including bioinformatics) is shown in a series of blog posts here: https://hpc.guix.info

Here's a paper on reproducible bioinfo pipelines that touches on why existing approaches usually don't go far enough: https://doi.org/10.1093/gigascience/giy123

Thanks for the quick response!
Ricardo

**Comment by kmezhoud** [comment]
Good Job!
It seems like a Docker concept. 
Let me know the change that I have to do for the License file.
Let me know if can I contribute to this work.
Thanks
Karim
