### ISSUE TITLE
"Error in htmlwidgets::shinyRenderWidget" when attempting to launch

### ISSUE THREAD

**Issue by lgerratana** [kmezhoud/bioCancer#2]
When I launch bioCancer the browser gets greyed out with the following error given in R

`Warning: Error in htmlwidgets::shinyRenderWidget: unused argument (evn = env)
  56: DiagrammeR::renderGrViz
  50: server [/Library/Frameworks/R.framework/Versions/3.6/Resources/library/bioCancer/app/server.R#67]
Error in htmlwidgets::shinyRenderWidget(expr = expr, outputFunction = grVizOutput,  : 
  unused argument (evn = env)`

Same scenario on different machines, both PC and Mac

**Comment by kmezhoud** [comment]
Sorry for delay. 
I missed the notification.
Yes It is related to Diagrammer package.
See discussion for this issue [here](https://github.com/rich-iannone/DiagrammeR/issues/373#issuecomment-600695918).
You have to use Diagrammer 1.01 or less.
