### ISSUE TITLE
cgdsr dependency

### ISSUE THREAD

**Issue by inodb** [kmezhoud/bioCancer#3]
Hi -

This is Ino from the cBioPortal team. We are looking to retire `cgdsr`, but we see `bioCancer` uses it quite a bit. How complex would it be to switch to using the new `cBioPortalData` package?

**Comment by kmezhoud** [comment]
Hi,
Sorry for the delay.
I have to replace all  functions from `cgdsr` package.
Is there an equivalents of theses examples of commands in `cBioPortalData` package?
I hope that the arguments of equivalents functions are the same....
Thanks

```r
cgds ← CGDS("http://cbioportal.org/public-portal/”)
Studies ← getCancerStudies(cgds)
GenProf ← getGeneticProfiles(cgds, "gbm_tcga_pub")
Cases ← getCaseLists(cgds,"gbm_tcga_pub")
ClinData← getClinicalData(cgds,"gbm_tcga_pub_all")
ProfData← getProfileData(cgds, "NF1",“gbm_tcga_pub_mrna", "gbm_tcga_pub_all")

```
