### ISSUE TITLE
Error in shinythemes::shinytheme("cerulean") : 

### ISSUE THREAD

**Issue by 3iqra** [kmezhoud/bioCancer#4]
Hi!
how can i fix this error. I am using R version 4.1.3

> bioCancer()
Loading required package: shiny
Error in shinythemes::shinytheme("cerulean") : 
  cerulean is not an available theme. Valid themes are: .
Stopped Radiant

**Comment by 3iqra** [comment]
I am using biocancer package for my final year project. Kindly, sir help me for fixing this error.

**Comment by kmezhoud** [comment]
Dear @3iqra,
cerulean shiny theme exists in current [version](https://github.com/rstudio/shinythemes).
Try to update/reinstall  `shinythemes` package.
Karim

**Comment by 3iqra** [comment]
Dear @kmezhoud ,
Sir,I appreciate your response and your time. Sir,I reinstall/update shinythemes package  but the error is still same.
 running bioCancer() on window 10,using R 4.1.3 and R studio 2022-3-10.

any help is highly appreciated.Thank you.
Iqra

**Comment by kmezhoud** [comment]
Dear @3iqra ,
Could you try this demo for themes?

```{r}
shinyApp(
  ui = navbarPage("United",
                  theme = shinythemes::shinytheme("cerulean"),  # <--- Specify theme here
                  tabPanel("Plot", "Plot tab contents..."),
                  navbarMenu("More",
                             tabPanel("Summary", "Summary tab contents..."),
                             tabPanel("Table", "Table tab contents...")
                  )
  ),
  server = function(input, output) { }
)


```

**Comment by 3iqra** [comment]
Dear @kmezhoud,
Yes, Sir I try many time, but its show  same error. I can not find the reason behind it.
thank you sir.

**Comment by kmezhoud** [comment]
> Dear @3iqra ,
> Could you try this demo for themes?
> 
> ```{r}
> shinyApp(
>   ui = navbarPage("United",
>                   theme = shinythemes::shinytheme("cerulean"),  # <--- Specify theme here
>                   tabPanel("Plot", "Plot tab contents..."),
>                   navbarMenu("More",
>                              tabPanel("Summary", "Summary tab contents..."),
>                              tabPanel("Table", "Table tab contents...")
>                   )
>   ),
>   server = function(input, output) { }
> )
> 
> 
> ```

Hi, try an other theme. I think that the issue is related to your OS.
Karim

**Comment by 3iqra** [comment]
Dear @kmezhoud ,

It does not work with any theme and give me same error. 
May be the issue is related to OS.
Thank you so much for all the help and time. I appreciate it.
Iqra

**Comment by kmezhoud** [comment]
Dear @3iqra ,
It means that the issue is not from bioCancer package.
Good luck!
Karim
